name: automated-blog-generator
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '25 14 * * 1-5'

env:
  APP_PROMPT: ${{ vars.APP_PROMPT }}

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install dependencies
        run: |
          npm install
      - name: show prompt
        run: |
          echo "${{ env.APP_PROMPT }}"
      - name: generate blog
        id: generate-blog
        run: |
          npm start
      - name: show result
        run: |
          echo "${{ steps.generate-blog.outputs.result }}"
