name: automated-blog-generator
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install dependencies
        run: |
          npm install
      - name: generate blog
        id: generate-blog
        run: |
          npm start
      - name: show output
        run: |
          echo "${{ steps.generate-blog.outputs.result }}"
